AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  SourceEmail:
    Description: Email From address that sends the email notifications.
    Type: String
Resources:
  EmailNotificationLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: FileUploadedAlert.lambda_handler
      CodeUri: Function
      Runtime: python3.9
      Timeout: 300
      MemorySize: 128
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonSESFullAccess
        - AmazonS3FullAccess
      Environment:
        Variables:
          SOURCE_ADDRESS: !Ref SourceEmail
          SUBJECT: "File upload successful"
          BODY: "The file {file} has successfully uploaded to S3."
